parameters:
  systemcheck.api.entity.user: Systemcheck\ContaoApiBundle\Entity\User
  systemcheck.api.entity.member: Systemcheck\ContaoApiBundle\Entity\Member
  secret: 'okend23873hgf8n2873zedh2838hbcd08237cb'