api:
  resource: "@SystemcheckContaoApiBundle/Controller"
  type: annotation

controller:
    resource: "@SystemcheckContaoApiBundle/Controller"
    type: annotation

api_login_check:
    path: /api/login_check
    methods: ['POST']

auth:
    path: /auth
    methods: ['POST']