services:
  _defaults:
        autowire: true
        autoconfigure: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]


  Systemcheck\ContaoApiBundle\:
    resource: '../../{Controller,EventListener}/*'
    autowire: true
    autoconfigure: true
    public: false

  systemcheck.api.backend.api_app:
    public: true
    class: Systemcheck\ContaoApiBundle\Backend\ApiApp
    arguments:
      - "@contao.framework"
  systemcheck.api.routing.matcher:
    class: Symfony\Component\HttpFoundation\RequestMatcher
    calls:
      - ["matchAttribute", ["_scope", "api"]]
  systemcheck.api.routing.login.member.matcher:
    class: Symfony\Component\HttpFoundation\RequestMatcher
    calls:
      - ["matchAttribute", ["_scope", "api_login_member"]]
  
  systemcheck.api.routing.login.user.matcher:
    class: Symfony\Component\HttpFoundation\RequestMatcher
    calls:
      - ["matchAttribute", ["_scope", "api_login_user"]]

  systemcheck.api.jwt_coder:
    class: Systemcheck\ContaoApiBundle\Api\Security\JWTCoder
    arguments:
      - "%secret%"
  Systemcheck\ContaoApiBundle\Security\JWTCoder: '@systemcheck.api.jwt_coder'

  systemcheck.security.api_authenticator:
    class:  Systemcheck\ContaoApiBundle\Security\TokenAuthenticator
    arguments:
      - "@contao.framework"
      - "@systemcheck.api.jwt_coder"
      - "@translator"
  systemcheck.api.security.user_provider:
    class: Systemcheck\ContaoApiBundle\Security\User\UserProvider
    arguments:
      - "@contao.framework"
      - Contao\FrontendUser
      - "@translator"

  systemcheck.api.security.username_password_authenticator:
    class: Systemcheck\ContaoApiBundle\Security\UsernamePasswordAuthenticator
    arguments:
      - "@contao.framework"
      - "@systemcheck.api.jwt_coder"
      - "@translator"

  
  

  systemcheck.api.resource.default:
    class: Systemcheck\ContaoApiBundle\ApiResource\CalendarEventResource
    arguments:
      - "calendar_event"
      - "@contao.data_collector"
    tags:
      - { name: systemcheck.api.resource, alias: default}

  systemcheck.api.resource.calendar_event:
    class: Systemcheck\ContaoApiBundle\ApiResource\CalendarEventResource
    arguments:
      - "calendar_event"
      - "@contao.data_collector"
    tags:
      - { name: systemcheck.api.resource, alias: calendar_event}
  systemcheck.api.resource.member:
    class: Systemcheck\ContaoApiBundle\ApiResource\MemberResource
    arguments:
      - "member"
      - "@contao.data_collector"
    tags:
      - { name: systemcheck.api.resource, alias: member}

  systemcheck.api.resource.events:
    class: Systemcheck\ContaoApiBundle\ApiResource\EventResource
    arguments:
      - "events"
      - "@contao.data_collector"
    tags:
      - { name: systemcheck.api.resource, alias: events}

  systemcheck.api.resource.foods:
    class: Systemcheck\ContaoApiBundle\ApiResource\EventResource
    arguments:
      - "foods"
      - "@contao.data_collector"
    tags:
      - { name: systemcheck.api.resource, alias: foods}

  systemcheck.api.model.app:
    class: Systemcheck\ContaoApiBundle\Model\ApiAppModel
    public: true
    shared: false
  systemcheck.api.util.api_util:
    class: Systemcheck\ContaoApiBundle\Util\ApiUtil
    public: true

  Systemcheck\ContaoApiBundle\Backend\AppApi:
    arguments:  
      - "@contao.framework"

  systemcheck.security.json_user_provider:
        class: Systemcheck\ContaoApiBundle\Security\User\JsonUserProvider
        arguments:
            - '@contao.framework'
            - Contao\FrontendUser

  Systemcheck\ContaoApiBundle\Controller\ResourceController:
    tags:
          -
            name: contao.frontend_module
            category: aiDesigner
            template: formdata
            type: 'Backend Migration Controller'
            _scope: 'api'
    arguments:
            - '@translator'    
            - '@doctrine.dbal.default_connection'
            - '@security.helper'
            #- '@lexik_jwt_authentication.jwt_manager'
            - '@systemcheck.api.manager.resource'
            #- '@systemcheck.api.resource.calendar_event'
            #- '@twig'
            #- '@contao.routing.scope_matcher'



  #systemcheck.api.manager.resource:
   # class: Systemcheck\ContaoApiBundle\Manager\ApiResourceManager
    #public: true
    #arguments:
    #  - "@contao.framework"
  #Systemcheck\ContaoApiBundle\Manager\ApiResourceManager: '@systemcheck.api.manager.resource'
  Systemcheck\ContaoApiBundle\Manager\ApiResourceManager: '@systemcheck.api.manager.resource'
  systemcheck.api.manager.resource:
        public: true
        #synthetic: true
        class: Systemcheck\ContaoApiBundle\Manager\ApiResourceManager
        #tags:
            #- { name: 'contao.callback', method: 'choices', table: 'tl_api_app', target: 'fields.field.options', priority: -1 }
        arguments: 
            - "@contao.framework"
            - "@parameter_bag"
            #- "@systemcheck.api.util.api_util"

  